# Generated by Django 3.2.6 on 2022-06-16 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 16, 13, 39, 42, 749575, tzinfo=utc)),
        ),
    ]
