# Generated by Django 3.2.6 on 2022-06-16 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_alter_alquiler_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 16, 13, 48, 44, 632735, tzinfo=utc)),
        ),
    ]
